In [1]:
import numpy as np

# operações escalares simples
### + - * /
### += , *=   modify an existing array 

In [2]:
A = np.array([ [1, 2, 0, -4],  [0, 2, 3, -1],  [1, 0, 3,  0] ])
B = np.array([ [-1,  0,  2], [ 0, -1, -2] ])
C = np.array([ [ 1,  0,  2], [ 1,  3,  0] ])
D = np.array([ 3,  5,  2])

In [3]:
A + 1

array([[ 2,  3,  1, -3],
       [ 1,  3,  4,  0],
       [ 2,  1,  4,  1]])

In [4]:
B * 3

array([[-3,  0,  6],
       [ 0, -3, -6]])

In [5]:
C ** 3

array([[ 1,  0,  8],
       [ 1, 27,  0]], dtype=int32)

In [6]:
B * C 
# elementwise product array 

array([[-1,  0,  4],
       [ 0, -3,  0]])

In [7]:
(B + 10) / ((C ** 2) + 10)

array([[ 0.81818182,  1.        ,  0.85714286],
       [ 0.90909091,  0.47368421,  0.8       ]])

# operações escalares propagadas

In [8]:
B / D

array([[-0.33333333,  0.        ,  1.        ],
       [ 0.        , -0.2       , -1.        ]])

In [9]:
A.T * D

array([[  3,   0,   2],
       [  6,  10,   0],
       [  0,  15,   6],
       [-12,  -5,   0]])

In [10]:
C + D

array([[4, 5, 4],
       [4, 8, 2]])

# operações vetoriais

In [11]:
B.dot(D)
# OR np.dot(B, D) 
# matrix product array 

array([ 1, -9])

In [12]:
B.dot(D.reshape([3,1]))

array([[ 1],
       [-9]])

In [13]:
np.dot(A.T, B.T)

array([[ 1, -2],
       [-2, -2],
       [ 6, -9],
       [ 4,  1]])