In [2]:
import numpy as np

In [7]:
x=1
y=2
z=3

In [9]:
#1D
a1d = np.array([x,y,z])
list = [x,y,z]
alist = np.array(list)
tuple = (x,y,z)
atuple = np.array(tuple)
#only 1 data type

In [12]:
#2D
a2d = np.array([[x,y,z] , [4,5,6]])
listoflists = [ list , [4,5,6] ]
alistoflists = np.array(listoflists)
listofarrays = [ alistoflists , np.array ( [4,5,6] ) ]
alistofarrays = np.array(listofarrays)

In [13]:
x1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x2d = np.array([ x1d,  x1d + 1,  x1d + 2,  x1d + 3, x1d + 4 ])
print(x2d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]]


In [ ]:
#array attributes 
ndim, shape, size
dtype, data, itemsize

In [15]:
x1d.ndim

1

In [16]:
x1d.shape

(10,)

In [17]:
x1d.size

10

In [18]:
x2d.dtype

dtype('int32')

In [19]:
x2d.data

In [20]:
x2d.itemsize

4

In [21]:
#printing
print(np.arange(10000).reshape(100,100))
np.set_printoptions(threshold='nan')

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]
