In [1]:
import numpy as np

In [2]:
A = np.array([ [1, 2, 0, -4],  [0, 2, 3, -1],  [1, 0, 3,  0] ])
B = np.array([ [-1,  0,  2], [ 0, -1, -2] ])
C = np.array([ [ 1,  0,  2], [ 1,  3,  0] ])
D = np.array([ 3,  5,  2])

### concatenar

In [3]:
np.hstack((B, C))

array([[-1,  0,  2,  1,  0,  2],
       [ 0, -1, -2,  1,  3,  0]])

In [4]:
np.vstack((B, C))

array([[-1,  0,  2],
       [ 0, -1, -2],
       [ 1,  0,  2],
       [ 1,  3,  0]])

In [5]:
np.column_stack((B,C))

array([[-1,  0,  2,  1,  0,  2],
       [ 0, -1, -2,  1,  3,  0]])

### transpor

In [6]:
np.transpose(A)

array([[ 1,  0,  1],
       [ 2,  2,  0],
       [ 0,  3,  3],
       [-4, -1,  0]])

In [7]:
B.T

array([[-1,  0],
       [ 0, -1],
       [ 2, -2]])

### propagando operações numéricas

In [8]:
# sum, sort, min, max

In [10]:
#sum of each column
B.sum(axis=0)

array([-1, -1,  0])

In [11]:
#mean of each row
B.mean(axis=1) 

array([ 0.33333333, -1.        ])

In [12]:
#cumulative sum along each row
B.cumsum(axis=1) 

array([[-1, -1,  1],
       [ 0, -1, -3]], dtype=int32)

### propagando operações lógicas

In [ ]:
all, any

In [13]:
(B > 0).all(axis=1)

array([False, False], dtype=bool)

In [14]:
(B > 0).any(axis=1)

array([ True, False], dtype=bool)